#!/usr/bin/env bash
#
# gen-router.sh — 从 contracts IDL 再生成 core 的 hz 路由（gen/router/）
#
# 路由治理策略（2026-10-06 起）：
#   - gen/router/ 由 hz 从 IDL 再生成，"Code generated" 文件不再手工维护；
#     gen/router/*/middleware.go（鉴权接线）是唯一手工保留区，hz update 不会触碰。
#   - gen/handler/ 的既有实现是手工业务代码：hz update 只会为"IDL 新增方法"创建
#     新桩文件，既有文件最多被追加一行 model import（本脚本统一回退该噪音）。
#   - 模型不落在 core：模型真相源是 contracts（gen-model.sh 再生成到 contracts/gen/），
#     本脚本把 hz 的模型产物写进临时目录并在结束后删除。
#   - 路由守卫：bootstrap/routes_guard_test.go + ratelimit_bucket_test.go 以真实
#     注册路由为契约双向守卫，任何 IDL↔路由漂移会在 go test 时失败。
#
# 依赖: hz v0.9.7（scripts/install-tools.sh 同款）；IDL 来自相邻的 contracts 仓
# 用法:
#   ./scripts/gen-router.sh            # 全量再生成（工作区内需有 ../contracts/idl）
#   IDL_DIR=/path/to/idl ./scripts/gen-router.sh   # 显式指定 IDL 目录
set -euo pipefail
cd "$(dirname "$0")/.."

MODULE="github.com/pigeonbox/core"
HZ_VERSION="v0.9.7"

fail() { echo -e "\033[1;31m[ERROR]\033[0m $1" >&2; exit 1; }

command -v hz >/dev/null || fail "hz 未安装: go install github.com/cloudwego/hertz/cmd/hz@${HZ_VERSION}"

# 定位 contracts IDL（默认按工作区布局 ../contracts/idl）
IDL_SRC="${IDL_DIR:-$(pwd)/../contracts/idl}"
[ -d "$IDL_SRC" ] || fail "IDL 目录不存在: $IDL_SRC（工作区内应有相邻 contracts 仓，或 IDL_DIR=/path/to/idl）"

# hz 插件按 out_dir 相对解析 IDL，拷贝进仓内临时目录再跑
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
cp -R "$IDL_SRC" "$WORK/idl"

# .hz 元数据（旧版 key:value 格式；routerDir 决定路由落点 gen/router）
cat > .hz << EOF
// Code generated by hz. DO NOT EDIT.

hz version: ${HZ_VERSION}
handlerDir: gen/handler
modelDir: hzmodel
routerDir: gen/router
EOF

# 仅处理带 service 定义的 IDL（纯 struct 文件随 include 自动带出）
IDLS=()
for f in "$WORK"/idl/*.thrift "$WORK"/idl/http/*.thrift; do
  [ -f "$f" ] || continue
  if grep -qE '^[[:space:]]*service[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\{' "$f"; then
    IDLS+=("$f")
  fi
done
[ ${#IDLS[@]} -gt 0 ] || fail "未找到带 service 定义的 thrift IDL"

echo "==> 共 ${#IDLS[@]} 个 IDL，再生成路由（middleware.go 不受影响）..."
for f in "${IDLS[@]}"; do
  echo "  - hz update: $(basename "$f")"
  hz update --sort_router --idl "$f" --module "$MODULE" --out_dir . \
    --handler_dir gen/handler --model_dir hzmodel -I "$WORK/idl" \
    > /dev/null
done

# 清理：模型临时目录 + handler 被追加的 hzmodel import 噪音（handler 归手工所有）
rm -rf hzmodel
# 仅摘除 hz update 追加的 hzmodel import 行（模型真相源在 contracts）。
# 不可整文件 git checkout——会连带清掉未提交的手工 handler 实现
# （2026-10-09 事故：用户分享组 5 个已实现 handler 被本循环整文件回退）。
# 仅删 import 规格行(可带别名的 "…/hzmodel" 字面量独占一行);含 hzmodel
# 字样的手写注释必须存活——旧 /hzmodel/d 全行匹配会误删(2026-10-10 IDL
# 迁移实测吞掉一句手工注释)。
git diff --name-only -- gen/handler | while read -r f; do
  if grep -q 'hzmodel' "$f"; then
    sed -i '' -E '/^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*[[:space:]]+)?"[^"]*\/hzmodel\/[[:space:]]*$/d' "$f"
  fi
done

echo "✓ 已再生成 gen/router/。自检："
echo "  git diff gen/router/   # 应仅排序/嵌套风格或真实 IDL 变更；middleware.go 不应出现"
echo "  go test ./bootstrap/   # 路由守卫（TestRegisteredRoutesMatchContract 等）必须绿"
